# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.2.2.9019
    hooks:
    -   id: style-files
        args: [--style_pkg=styler.mlr, --style_fun=mlr_style]
        additional_dependencies:
        - mlr-org/styler.mlr
    -   id: roxygenize
        additional_dependencies:
        -    backports
        -    checkmate
        -    coro
        -    data.table
        -    fs
        -    luz
        -    magick
        -    methods
        -    mlr3
        -    mlr3misc
        -    mlr3pipelines
        -    paradox
        -    progress
        -    R6
        -    rlang
        -    torch
        -    torchvision
        -    zeallot
        -    lgr
        -    tabnet
        -    zip
    # codemeta must be above use-tidy-description when both are used
    # -   id: codemeta-description-updated
    -   id: use-tidy-description
    # -   id: lintr
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: deps-in-desc
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: end-of-file-fixer
        exclude: '\.Rd'
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        exclude: inst/toytask
        # `exclude: <regex>` to allow committing specific files
